quiz3_ideas/config/routes.rb
Rails.application.routes.draw do

  resources :comments

  root "ideas#index"

  resources :ideas do
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only:[:create, :destroy]
    resources :joins, only:[:create, :destroy]
  end

  resources :users, only:[:new, :create]

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end

end

quiz3_ideas/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

  can :manage, Idea do |idea|
    user == idea.user
  end

  can :destroy, Like do |like|
    user == like.user
  end

  can :like, Idea do |idea|
    user != idea.user
  end

  cannot :like, Idea do |idea|
    user == idea.user
  end

  can :destroy, Join do |join|
    user == join.user
  end

  can :join, Idea do |idea|
    user != idea.user
  end

  cannot :join, Idea do |idea|
    user == idea.user
  end

  end

end

quiz3_ideas/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quiz3_ideas/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
end

quiz3_ideas/app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader
  
  has_many :likes, dependent: :destroy
  # has_many :users, through: :likes

  has_many :joins, dependent: :destroy
  # has_many :members, through: :joins, source: :join

  has_many :comments, dependent: :destroy

  def like_for(user)
    likes.find_by_user_id user
  end

  def join_for(user)
    joins.find_by_user_id user
  end

end

quiz3_ideas/app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :user_id, uniqueness: {scope: :idea_id,
                      message: "Joined already"}
end

quiz3_ideas/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :user_id, uniqueness: {scope: :idea_id,
                      message: "Liked already"}
end

quiz3_ideas/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :ideas, dependent: :nullify

  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea

  has_many :joins, dependent: :destroy
  has_many :joined_ideas, through: :joins, source: :idea

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    format: VALID_EMAIL_REGEX

# Avatar
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def full_name
    "#{first_name} #{last_name}".squeeze(" ").strip.titleize
  end

end

quiz3_ideas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find session[:user_id] if user_signed_in?
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to new_session_path unless user_signed_in?
  end

end

quiz3_ideas/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new params.require(:comment).permit(:body)
    @idea = Idea.find params[:idea_id]
    @comment.idea = @idea
    if @comment.save
    redirect_to(idea_path(@idea), notice: "Comment created")
    else
    render :new
    end
  end

  def destroy
  comment = Comment.find params[:id]
  comment.destroy
  redirect_to(idea_path(@idea), notice: "Comment deleted")
  end


end

quiz3_ideas/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit, :update, :destroy]

  def new
    @idea = Idea.new
  end

  def create
    @idea        = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to idea_path(@idea), notice: "Idea created successfully"
    else
      render :new
    end
  end

  def show
    @members = @idea.joins
    @comment = Comment.new
  end

  def index
    @ideas = Idea.all
  end

  def edit
  end

  def update
    if @idea.update idea_params
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path
  end

  private
  def find_idea
    @idea = Idea.find params[:id]
  end

  def idea_params
    params.require(:idea).permit([:title, :body, :user_id, :image ])
  end

  def authorize!
    redirect_to(root_path, alert: "access defined") unless can? :manage, @idea
  end

end

quiz3_ideas/app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_action :authenticate_user!

  def create
    idea = Idea.find params[:idea_id]
    join = Join.new user:current_user, idea:idea
    if !(can? :join, idea)
      redirect_to root_path, alert: "access denied"
    elsif join.save
      redirect_to idea_path(idea), notice: "Thanks for joining"
    else
      redirect_to idea_path(idea), alert: join.errors.full_messages.join(", ")
    end
  end

  def destroy
    idea = Idea.find params[:idea_id]
    join = Join.find params[:id]
    if can? :destroy, join
      join.destroy
      redirect_to idea_path(idea), notice: "Not Joined Anymore!"
    else
      redirect_to root_path, alert: "access denied!"
    end
  end


end

quiz3_ideas/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    idea = Idea.find params[:idea_id]
    like = Like.new user:current_user, idea:idea
    if !(can? :like, idea)
      redirect_to root_path, alert: "access denied"
    elsif like.save
      AnswerMailer.notify_idea_owner(like).deliver_later
      redirect_to idea_path(idea), notice: "Thanks for liking"
    else
      redirect_to idea_path(idea), alert: like.errors.full_messages.join(", ")
    end
  end

  def destroy
    idea = Idea.find params[:idea_id]
    like = Like.find params[:id]
    if can? :destroy, like
      like.destroy
      redirect_to idea_path(idea), notice: "Like removed!"
    else
      redirect_to root_path, alert: "access denied!"
    end
  end

end

quiz3_ideas/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Signed In"
      else
        flash[:alert] = "Wrong Credentials"
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed Out"
  end

end

quiz3_ideas/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thanks for signing up"
    else
      flash[:alert] = "Fix errors below"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

end

quiz3_ideas/app/helpers/application_helper.rb
module ApplicationHelper
  
end

quiz3_ideas/app/helpers/comments_helper.rb
module CommentsHelper
end

quiz3_ideas/app/helpers/ideas_helper.rb
module IdeasHelper
end

quiz3_ideas/app/helpers/joins_helper.rb
module JoinsHelper
end

quiz3_ideas/app/helpers/likes_helper.rb
module LikesHelper
end

quiz3_ideas/app/helpers/sessions_helper.rb
module SessionsHelper
end

quiz3_ideas/app/helpers/users_helper.rb
module UsersHelper
end

quiz3_ideas/app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>
<%= @idea.errors.full_messages.join(", ") %>
<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>

<% end %>

quiz3_ideas/app/views/ideas/index.html.erb
<h1>All Ideas</h1>
<% @ideas.each do |idea| %>
<%= link_to idea.title, idea_path(idea)%>
  <hr>
<% end %>

quiz3_ideas/app/views/ideas/new.html.erb
<h1>Submit a new idea</h1>
<%= @idea.errors.full_messages.join(", ") %>
<%= form_for @idea do |f| %>

<div>
  <%= f.label :title%>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :body%>
  <%= f.text_area :body %>
</div>

<div>
  <%= f.label :image %>
  <%= f.file_field :image %>
</div>


<%= f.submit %>

<% end %>

quiz3_ideas/app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p>
  <%= @idea.body %>
  <%= image_tag @idea.image %>

</p>
<h4>By <%= @idea.user.first_name.capitalize%></h4>
<%= link_to "Edit", edit_idea_path(@idea) %>
|
<%= link_to "Delete", idea_path(@idea),
                        method: :delete,
                        data: {confirm: "Are you sure?"}%>
|
<!-- Like -->
<% if can? :like, @idea %>
  <% user_like = @idea.like_for current_user %>
  <% if user_like.present? %>
  <%= link_to "Unlike", idea_like_path(@idea, user_like),
                        method: :delete %>
  <% else %>
  <%= link_to "Like", idea_likes_path(@idea),
                      method: :post %>
  <% end %>
<% else %>
Like
<% end %>
(<%= pluralize @idea.likes.count, "like" %>)

|
<!-- Join -->
<% if can? :join, @idea %>
  <% member_join = @idea.join_for current_user %>
  <% if member_join.present? %>
  Joined
  <%= link_to "Unjoin", idea_join_path(@idea, member_join),
                        method: :delete %>
  <% else %>
  <%= link_to "Join", idea_joins_path(@idea),
                        method: :post %>
  <% end %>
<% else %>
Join
<% end %>
<br>
These are all the members who have joined this idea:
<ul>
<% @members.each do |member|%>
<li> <%= User.find(member.user_id).first_name %> </li>
<% end %>
</ul>
<!-- Comments -->
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for [@idea, @comment] do |f| %>
<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %>

<!-- Displaying comments -->
<h2>Comments</h2>
<% @idea.comments.each do |comm| %>
<%= comm.body %>
<%= link_to "delete", idea_comment_path(@idea, comm),
                      method: :delete,
                      data: {confirm: "Are you sure you want to delete the comment?"} %>
<hr>
<% end %>

quiz3_ideas/app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up" %>

<% end %>